OSCAR_MAPPING = {
    'ACTOR': 'Best Actor',
    'ACTOR IN A LEADING ROLE': 'Best Actor',
    'ACTOR IN A SUPPORTING ROLE': 'Best Supporting Actor',
    'ACTRESS': 'Best Actress',
    'ACTRESS IN A LEADING ROLE': 'Best Actress',
    'ACTRESS IN A SUPPORTING ROLE': 'Best Supporting Actress',
    'ANIMATED FEATURE FILM': 'Best Animated Feature Film',
    'ART DIRECTION': 'Best Production Design',
    'ART DIRECTION (Black-and-White)': 'Best Production Design',
    'ART DIRECTION (Color)': 'Best Production Design',
    'ASSISTANT DIRECTOR': 'Best Assistant Director',
    'BEST PICTURE': 'Best Picture',
    'CINEMATOGRAPHY': 'Best Cinematography',
    'CINEMATOGRAPHY (Black-and-White)': 'Best Cinematography',
    'CINEMATOGRAPHY (Color)': 'Best Cinematography',
    'COSTUME DESIGN': 'Best Costume Design',
    'COSTUME DESIGN (Black-and-White)': 'Best Costume Design',
    'COSTUME DESIGN (Color)': 'Best Costume Design',
    'DANCE DIRECTION': 'Best Dance Direction',
    'DIRECTING': 'Best Director',
    'DIRECTING (Comedy Picture)': 'Best Director, Comedy Picture',
    'DIRECTING (Dramatic Picture)': 'Best Director, Dramatic Picture',
    'DOCUMENTARY': 'Best Documentary Feature',
    'DOCUMENTARY (Feature)': 'Best Documentary Feature',
    'DOCUMENTARY (Short Subject)': 'Best Documentary Short Subject',
    'ENGINEERING EFFECTS': 'Best Engineering Effects',
    'FILM EDITING': 'Best Film Editing',
    'FOREIGN LANGUAGE FILM': 'Best International Feature Film',
    'INTERNATIONAL FEATURE FILM': 'Best International Feature Film',
    'MAKEUP': 'Best Makeup and Hairstyling',
    'MAKEUP AND HAIRSTYLING': 'Best Makeup and Hairstyling',
    'MUSIC (Adaptation Score)': 'Best Original Score',
    'MUSIC (Music Score of a Dramatic Picture)': 'Best Original Score',
    'MUSIC (Music Score of a Dramatic or Comedy Picture)': 'Best Original Score',
    'MUSIC (Music Score--substantially original)': 'Best Original Score',
    'MUSIC (Original Dramatic Score)': 'Best Original Score',
    'MUSIC (Original Music Score)': 'Best Original Score',
    'MUSIC (Original Musical or Comedy Score)': 'Best Original Musical or Comedy Score',
    'MUSIC (Original Score)': 'Best Original Score',
    'MUSIC (Original Score--for a motion picture [not a musical])': 'Best Original Score',
    'MUSIC (Original Song Score and Its Adaptation -or- Adaptation Score)': 'Best Original Score',
    'MUSIC (Original Song Score and Its Adaptation or Adaptation Score)': 'Best Original Score',
    'MUSIC (Original Song Score or Adaptation Score)': 'Best Original Score',
    'MUSIC (Original Song Score)': 'Best Original Score',
    'MUSIC (Original Song)': 'Best Original Song',
    'MUSIC (Score of a Musical Picture--original or adaptation)': 'Best Original Score',
    'MUSIC (Scoring of Music--adaptation or treatment)': 'Best Original Score',
    'MUSIC (Scoring of a Musical Picture)': 'Best Original Score',
    'MUSIC (Scoring)': 'Best Original Score',
    'MUSIC (Scoring: Adaptation and Original Song Score)': 'Best Original Score',
    'MUSIC (Scoring: Original Song Score and Adaptation -or- Scoring: Adaptation)': 'Best Original Score',
    'MUSIC (Song)': 'Best Original Song',
    'MUSIC (Song--Original for the Picture)': 'Best Original Song',
    'OUTSTANDING MOTION PICTURE': 'Best Picture',
    'OUTSTANDING PRODUCTION': 'Best Picture',
    'PRODUCTION DESIGN': 'Best Production Design',
    'SHORT FILM (Animated)': 'Best Animated Short Film',
    'SHORT FILM (Dramatic Live Action)': 'Best Live Action Short Film',
    'SHORT FILM (Live Action)': 'Best Live Action Short Film',
    'SHORT SUBJECT (Animated)': 'Best Animated Short Film',
    'SHORT SUBJECT (Cartoon)': 'Best Animated Short Film',
    'SHORT SUBJECT (Color)': 'Best Short Subject – Color',
    'SHORT SUBJECT (Comedy)': 'Best Short Subject – Comedy',
    'SHORT SUBJECT (Live Action)': 'Best Live Action Short Film',
    'SHORT SUBJECT (Novelty)': 'Best Short Subject – Novelty',
    'SHORT SUBJECT (One-reel)': 'Best Short Subject – 1 Reel',
    'SHORT SUBJECT (Two-reel)': 'Best Short Subject – 2 Reel',
    'SOUND': 'Best Sound',
    'SOUND EDITING': 'Best Sound Editing',
    'SOUND EFFECTS': 'Best Sound',
    'SOUND EFFECTS EDITING': 'Best Sound',
    'SOUND MIXING': 'Best Sound',
    'SOUND RECORDING': 'Best Sound',
    'SPECIAL EFFECTS': 'Best Visual Effects',
    'SPECIAL VISUAL EFFECTS': 'Best Visual Effects',
    'UNIQUE AND ARTISTIC PICTURE': 'Best Picture',
    'VISUAL EFFECTS': 'Best Visual Effects',
    'WRITING (Adaptation)': 'Best Adapted Screenplay',
    'WRITING (Adapted Screenplay)': 'Best Adapted Screenplay',
    'WRITING (Motion Picture Story)': 'Best Original Story',
    'WRITING (Original Motion Picture Story)': 'Best Original Story',
    'WRITING (Original Screenplay)': 'Best Original Screenplay',
    'WRITING (Original Story)': 'Best Original Story',
    'WRITING (Screenplay Adapted from Other Material)': 'Best Adapted Screenplay',
    'WRITING (Screenplay Based on Material Previously Produced or Published)': 'Best Adapted Screenplay',
    'WRITING (Screenplay Based on Material from Another Medium)': 'Best Adapted Screenplay',
    'WRITING (Screenplay Written Directly for the Screen)': 'Best Original Screenplay',
    'WRITING (Screenplay Written Directly for the Screen--based on factual material or on story material not previously published or produced)': 'Best Original Screenplay',
    'WRITING (Screenplay)': 'Best Original Screenplay',
    'WRITING (Screenplay--Original)': 'Best Original Screenplay',
    'WRITING (Screenplay--based on material from another medium)': 'Best Adapted Screenplay',
    'WRITING (Story and Screenplay)': 'Best Original Screenplay',
    'WRITING (Story and Screenplay--based on factual material or material not previously published or produced)': 'Best Original Screenplay',
    'WRITING (Story and Screenplay--based on material not previously published or produced)': 'Best Original Screenplay',
    'WRITING (Story and Screenplay--written directly for the screen)': 'Best Original Screenplay',
    'WRITING (Title Writing)': 'Best Title Writing'
}
