version: "3.7"
services:
  mao-db-mssql:
    container_name: mao-db-mssql
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "tbU(X1ID"

  # MySQL database backend
  mao-db:
    container_name: mao-db
    image: mysql:5.7.22
    environment:
      TZ: "Asia/Bangkok"
      MYSQL_DATABASE: "mao"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - "3306:3306"
    volumes:
      - ./database/dump:/docker-entrypoint-initdb.d # Dump loader
      - ./database/mysql-datadir:/var/lib/mysql # Default MySQL data directory: For persistence
      - ./database/config/custom.cnf:/etc/mysql/conf.d/custom.cnf # MySQL configuration file
    restart: unless-stopped
