# Generated by Django 3.1.4 on 2020-12-20 20:12

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(app.models.UpsertMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
            ],
            bases=(models.Model, app.models.UpsertMixin),
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasNickname', models.CharField(max_length=255, null=True)),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CollectiveAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ContentRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasDescription', models.CharField(max_length=255)),
            ],
            bases=(app.models.UpsertMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ContentRatingCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasValue', models.CharField(max_length=255)),
                ('isPartOf', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hasPart', to='app.contentrating')),
            ],
            bases=(app.models.UpsertMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isSettingFor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.award')),
            ],
        ),
        migrations.CreateModel(
            name='ActingSituation',
            fields=[
                ('situation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.situation')),
            ],
            bases=('app.situation',),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.place')),
                ('label', models.CharField(max_length=255)),
                ('alpha_2', models.CharField(max_length=2)),
                ('alpha_3', models.CharField(max_length=3)),
            ],
            bases=('app.place', app.models.UpsertMixin),
        ),
        migrations.CreateModel(
            name='FilmCast',
            fields=[
                ('collectiveagent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.collectiveagent')),
                ('isParticipantIn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.actingsituation')),
            ],
            bases=('app.collectiveagent',),
        ),
        migrations.CreateModel(
            name='FilmCrew',
            fields=[
                ('collectiveagent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.collectiveagent')),
            ],
            bases=('app.collectiveagent',),
        ),
        migrations.CreateModel(
            name='FilmMakingSituation',
            fields=[
                ('situation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.situation')),
                ('hasCast', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.filmcast')),
            ],
            bases=('app.situation',),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('agent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.agent')),
                ('hasName', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
            ],
            bases=('app.agent',),
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('wikidata_id', models.CharField(max_length=13)),
                ('hasSubGenre', models.ManyToManyField(null=True, related_name='isSubGenreOf', to='app.Genre')),
            ],
            bases=(models.Model, app.models.UpsertMixin),
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateReleased', models.CharField(max_length=255, null=True)),
                ('hasFeatureLengthInMinutes', models.IntegerField(null=True)),
                ('hasInitialReleaseYear', models.IntegerField(null=True)),
                ('hasTitle', models.CharField(max_length=255, null=True)),
                ('isAdult', models.BooleanField(null=True)),
                ('hasWikidataId', models.CharField(max_length=13, null=True)),
                ('avg_rating', models.CharField(max_length=255, null=True)),
                ('t_const', models.CharField(max_length=255, unique=True)),
                ('hasContentRating', models.ManyToManyField(null=True, to='app.ContentRatingCategory')),
                ('hasFilmingLocation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filming_location_of_films', to='app.place')),
                ('hasGenre', models.ManyToManyField(null=True, to='app.Genre')),
                ('hasLanguage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='language_of_films', to='app.language')),
                ('hasOriginalLanguage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_language_of_films', to='app.language')),
                ('hasPrequels', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hasSequels', to='app.film')),
                ('hasCountryOfOrigin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_country_of_films', to='app.country')),
            ],
        ),
        migrations.CreateModel(
            name='AwardCeremony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearHeld', models.IntegerField()),
                ('hasEditionNumber', models.IntegerField()),
                ('yearScreened', models.IntegerField()),
                ('hasAward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.award')),
            ],
            bases=(app.models.UpsertMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AwardCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('forOccupation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.occupation')),
            ],
            bases=(models.Model, app.models.UpsertMixin),
        ),
        migrations.AddField(
            model_name='award',
            name='hasAwardCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.awardcategory'),
        ),
        migrations.AddField(
            model_name='award',
            name='hasPart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.awardceremony'),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('agent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.agent')),
                ('hasGender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('non-binary', 'Non Binary')], max_length=255, null=True)),
                ('hasName', models.CharField(max_length=255, null=True)),
                ('n_const', models.CharField(max_length=255, null=True, unique=True)),
                ('eligibleFor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.award')),
                ('hasOccupation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.occupation')),
                ('isParticipantIn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.filmmakingsituation')),
            ],
            bases=('app.agent',),
        ),
        migrations.AddField(
            model_name='occupation',
            name='isOccupationof',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.person'),
        ),
        migrations.CreateModel(
            name='NominationSituation',
            fields=[
                ('situation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.situation')),
                ('win', models.BooleanField()),
                ('forFilm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.film')),
                ('hasAward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.award')),
                ('hasAwardCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.awardcategory')),
                ('hasAwardCeremony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.awardceremony')),
                ('isGivenTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.agent')),
            ],
            bases=(app.models.UpsertMixin, 'app.situation'),
        ),
        migrations.AddField(
            model_name='filmmakingsituation',
            name='hasCinematographer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cinematographer_of_film_making_situation_set', to='app.person'),
        ),
        migrations.AddField(
            model_name='filmmakingsituation',
            name='hasComposer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='composer_of_film_making_situation_set', to='app.person'),
        ),
        migrations.AddField(
            model_name='filmmakingsituation',
            name='hasCrew',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.filmcrew'),
        ),
        migrations.AddField(
            model_name='filmmakingsituation',
            name='hasDirector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='director_of_film_making_situation_set', to='app.person'),
        ),
        migrations.AddField(
            model_name='filmmakingsituation',
            name='hasFilm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.film'),
        ),
        migrations.AddField(
            model_name='filmmakingsituation',
            name='hasPart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.actingsituation'),
        ),
        migrations.AddField(
            model_name='filmmakingsituation',
            name='hasProducer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producer_of_film_making_situation_set', to='app.person'),
        ),
        migrations.AddField(
            model_name='filmcrew',
            name='isParticipantIn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.filmmakingsituation'),
        ),
        migrations.AddField(
            model_name='contentrating',
            name='appliesInCountry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.country'),
        ),
        migrations.AddField(
            model_name='collectiveagent',
            name='hasMember',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.person'),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasGender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('non-binary', 'Non Binary')], max_length=255, null=True)),
                ('hasImportance', models.CharField(choices=[('main', 'Main'), ('side', 'Side'), ('extra', 'Extra')], max_length=255, null=True)),
                ('hasName', models.CharField(max_length=255, null=True)),
                ('actedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.person')),
            ],
        ),
        migrations.AddField(
            model_name='award',
            name='hasSetting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.nominationsituation'),
        ),
        migrations.AddField(
            model_name='award',
            name='presentedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.organization'),
        ),
        migrations.AddField(
            model_name='actingsituation',
            name='hasActor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.person'),
        ),
        migrations.AddField(
            model_name='actingsituation',
            name='hasCharacter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.character'),
        ),
        migrations.AddField(
            model_name='actingsituation',
            name='hasFilm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.film'),
        ),
        migrations.AddField(
            model_name='actingsituation',
            name='isPartOf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.filmmakingsituation'),
        ),
        migrations.CreateModel(
            name='MovieStudio',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.organization')),
                ('locatedIn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.place')),
            ],
            bases=('app.organization',),
        ),
    ]
