# Generated by Django 3.1.4 on 2020-12-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='actsIn',
            new_name='isParticipantIn',
        ),
        migrations.AlterField(
            model_name='person',
            name='n_const',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
