# Generated by Django 3.1.3 on 2020-12-21 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContentRatingCategory',
            new_name='ContentRatingClassification',
        ),
    ]
