# Generated by Django 3.1.3 on 2020-12-21 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201221_0512'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContentRating',
            new_name='ContentRatingCategory',
        ),
    ]
