# Generated by Django 3.1.3 on 2020-12-21 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201221_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentratingclassification',
            name='isPartOf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasPart', to='app.contentratingcategory'),
        ),
    ]
